---
- import_tasks: swap.yml
  tags:
    - master
    - node

- import_tasks: kernel.yml
  tags:
    - master
    - node

- import_tasks: hosts.yml
  tags:
    - master
    - node

- import_tasks: pkg.yml
  tags: 
    - master
    - node

# ansible server pull && tag && push to repo 
# ansible client pull from repo
- import_tasks: pull-images.yml
  tags:
    - master
    - node

