---
- name: close swap
  shell: |
    swapoff -a
  tags:
    - master
    - node
  args:
    warn: no

- name: disable swap in fstab
  shell: |
    sed -i.bak "/swap/ s/^/#/g " {{ ETC_FSTAB }}
  args:
    warn: no



