---
# defaults file for kube-node-init

TMP_FILE_KUBE_ALIYUN_REPO: "kube-aliyun.repo"

KUBE_REPO_LOCAL: "nightkid"
KUBE_REPO_DEFAULT: "k8s.gcr.io"

KERNEL_MOD_IP_VS_NAME: "ipvs.modules"
KERNEL_MOD_IP_VS:
- ip_vs
- ip_vs_rr
- ip_vs_wrr
- ip_vs_sh
- nf_conntrack_ipv4
TMP_KERNEL_MOD_IP_VS: "etc_sysconfig_modules_ipvs.modules.yml"

BIN_KUBEBOX_DOWNLOAD: 
  url: "https://github.com/astefanutti/kubebox/releases/download/v0.3.2/kubebox-linux"
  dest: "/usr/local/bin/kubebox"
  mode: 0755

POD_NETWORK: "10.244.0.0/16"
SERVICE_NETWORK: "192.168.251.0/24"