- name: init kubernetes cluster
  shell: |
    kubeadm init \
    --apiserver-advertise-address={{ ansible_ssh_host }} \
    --pod-network-cidr={{ POD_NETWORK }} \
    --service-cidr={{ SERVICE_NETWORK }} \
    --kubernetes-version=v{{ KUBERNETS_VERSION }}
  when: kube_role=='master'
  args:
    warn: no
  tags:
    - master

- name: copy kube-config conf
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  when: kube_role=='master'
  args:
    warn: no
  tags:
    - master

- name: config master flannel network 
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: kube_role=='master'
  tags:
    - master

- name: gen kubeadm join command
  shell: |
    kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  ignore_errors: True
  run_once: True
  when: kube_role=='master'
  tags:
    - node