---
# tasks file for docker

- name: uninstall old version
  yum: 
    name={{ item }}
    state=absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: install dep
  yum:
    name={{ item }}
    state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker repo
  copy:
    src="docker-ce.repo"
    dest="/etc/yum.repos.d/docker-ce.repo"

- name: install docker-ce
  yum: 
    name=docker-ce
    state=present

- name: start docker service
  service:
    name=docker
    state=started













